/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalakiGame.Napakalaki;

/**
 *
 * @author joaquin
 */
public class NapakalakiView extends javax.swing.JFrame {

    /**
     * Creates new form NapakalakiView
     */
    private Napakalaki napakalakiModel = Napakalaki.getInstance();
    
    
    public NapakalakiView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki n){
    
        napakalakiModel = n;
        this.playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        this.monsterView2.setMonster(napakalakiModel.getCurrentMonster());
        this.playerView1.setNapakalaki(n);
        this.monsterView2.setVisible(false);
        this.jBcombat.setEnabled(false);
        this.jBnextTurn.setEnabled(false);
        this.jBmeetMonster.setEnabled(true);
        this.jLresultado.setText("ninguno");
        repaint();
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLresultado = new javax.swing.JLabel();
        jBmeetMonster = new javax.swing.JButton();
        jBcombat = new javax.swing.JButton();
        jBnextTurn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        playerView1 = new GUI.PlayerView();
        monsterView2 = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Resultado del combate");

        jLresultado.setText("ninguno");

        jBmeetMonster.setText("Meet the monster");
        jBmeetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmeetMonsterActionPerformed(evt);
            }
        });

        jBcombat.setText("Combat");
        jBcombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcombatActionPerformed(evt);
            }
        });

        jBnextTurn.setText("Next turn");
        jBnextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnextTurnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("NAPAKALAKI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBmeetMonster))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLresultado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBnextTurn)
                                .addGap(18, 18, 18)
                                .addComponent(jBcombat)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLresultado)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBmeetMonster)
                            .addComponent(jBnextTurn)
                            .addComponent(jBcombat)))
                    .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBmeetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmeetMonsterActionPerformed
        this.monsterView2.setVisible(true);
        this.jBcombat.setEnabled(true);
    }//GEN-LAST:event_jBmeetMonsterActionPerformed

    private void jBcombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcombatActionPerformed
        this.jBnextTurn.setEnabled(true);
        this.jBcombat.setEnabled(false);
        this.jBmeetMonster.setEnabled(false);
        this.jLresultado.setText(napakalakiModel.developCombat().toString());
    }//GEN-LAST:event_jBcombatActionPerformed

    private void jBnextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnextTurnActionPerformed
        boolean pasar = napakalakiModel.nextTurn();
        if(!pasar)
            this.jLresultado.setText("cumple el mal rollo primero");
        else
        this.setNapakalaki(napakalakiModel);
    }//GEN-LAST:event_jBnextTurnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcombat;
    private javax.swing.JButton jBmeetMonster;
    private javax.swing.JButton jBnextTurn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLresultado;
    private GUI.MonsterView monsterView2;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
