/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import napakalakiGame.Napakalaki;
import napakalakiGame.Player;
import napakalakiGame.Treasure;

/**
 *
 * @author papa
 */
public class PlayerView extends javax.swing.JPanel {

    /**
     * Creates new form PlayerView
     */
    private Player playerModel;
    private Napakalaki napakalakiModel = Napakalaki.getInstance();
    
    public PlayerView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki p){
         napakalakiModel=p;
    
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel){
        // se recorren los tesoros que contienen el panel, almacenando en un vector aquellos que estan selecionados
        //finalmente se devuelve dicho vector
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for(Component c : aPanel.getComponents()){
            tv = (TreasureView) c;
            if (tv.isSelected())
                output.add(tv.getTreasure());
        }
        return output;
    }
    
    public void setPlayer(Player p){
         playerModel = p;
         //dar valor
         this.jLnombre.setText(playerModel.getName());
         this.jLnivel.setText(Integer.toString(playerModel.getLevels()));
         this.jLnCombate.setText(Integer.toString(playerModel.getCombatLevel()));
         this.jLenemy.setText(playerModel.getEnemy().getName());
         this.jLesSectario.setText(Boolean.toString(playerModel.getConvertido()));
         //this.pendingBadConsequenceView1.setBadConsequence(playerModel.getBC());
         this.jLnSectarios.setText(Integer.toString(playerModel.getTotalCultistPlayers()));
         // a continuacion se actualizan sus tesoros
         this.fillTreasurePanel(jPvisibleTreasures, playerModel.getVisibleTreasures());
         this.fillTreasurePanel(jPhiddenTreasures, playerModel.getHiddenTreasures());
         this.jBsteal.setEnabled(false);
         if(playerModel.canISteal())
             this.jBsteal.setEnabled(true);
         repaint();
         revalidate();
    }
    
    private void fillTreasurePanel (JPanel aPanel , ArrayList<Treasure> aList){
         //se elimina la informacion antigua , si la hubiera
         aPanel.removeAll();
         // se recorre  la lista de tesoros construyendo y añadiendo sus vistas al panel
         for(Treasure t : aList){
             TreasureView aTreasureView = new TreasureView();
             aTreasureView.setTreasure(t);
             aTreasureView.setVisible(true);
             aPanel.add(aTreasureView);
         }
         //se fuerza la actualizacion visual del panel
         aPanel.repaint();
         aPanel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLnivel = new javax.swing.JLabel();
        jlavelg = new javax.swing.JLabel();
        jLnCombate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLenemy = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLesSectario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLnSectarios = new javax.swing.JLabel();
        jPvisibleTreasures = new javax.swing.JPanel();
        jPhiddenTreasures = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBsteal = new javax.swing.JButton();
        jBdiscardTreasures = new javax.swing.JButton();
        jBmakeVisible = new javax.swing.JButton();
        jBdAtreasures = new javax.swing.JButton();
        pendingBadConsequenceView2 = new GUI.PendingBadConsequenceView();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Jugador");

        jLabel2.setText("nombre");

        jLnombre.setText("ninguno");

        jLabel3.setText("nivel");

        jLnivel.setText("0");

        jlavelg.setText("nivel de combate");

        jLnCombate.setText("0");

        jLabel4.setText("enemigo");

        jLenemy.setText("ninguno");

        jLabel5.setText("Es sectario");

        jLesSectario.setText("no");

        jLabel6.setText("Nº sectarios");

        jLnSectarios.setText("ninguno");

        jPvisibleTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPhiddenTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPhiddenTreasures.setAutoscrolls(true);
        jPhiddenTreasures.setLayout(new java.awt.GridLayout());
        jPhiddenTreasures.add(jSeparator1);

        jLabel7.setText("Visible Treasures");

        jLabel8.setText("Hidden Treasures");

        jBsteal.setText("Steal Treasure");
        jBsteal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBstealActionPerformed(evt);
            }
        });

        jBdiscardTreasures.setText("Discard Treasures");
        jBdiscardTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdiscardTreasuresActionPerformed(evt);
            }
        });

        jBmakeVisible.setText("Make visible");
        jBmakeVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmakeVisibleActionPerformed(evt);
            }
        });

        jBdAtreasures.setText("Discard all treasures");
        jBdAtreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdAtreasuresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLnivel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jLnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlavelg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLnCombate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPvisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jBsteal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBmakeVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBdAtreasures)
                                            .addComponent(jBdiscardTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLnSectarios)
                                            .addComponent(jLesSectario)
                                            .addComponent(jLenemy, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pendingBadConsequenceView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPhiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jPhiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendingBadConsequenceView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel7))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLnombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLnivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlavelg)
                            .addComponent(jLnCombate)))
                    .addComponent(jPvisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLenemy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLesSectario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLnSectarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsteal)
                    .addComponent(jBdiscardTreasures))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBmakeVisible)
                    .addComponent(jBdAtreasures))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBmakeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmakeVisibleActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures(this.jPhiddenTreasures);
        napakalakiModel.makeTreasuresVisible(selHidden);
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jBmakeVisibleActionPerformed

    private void jBdiscardTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdiscardTreasuresActionPerformed
        ArrayList<Treasure> discardHidden = getSelectedTreasures(this.jPhiddenTreasures);
        ArrayList<Treasure> discardVisible = getSelectedTreasures(this.jPvisibleTreasures);
        napakalakiModel.discardVisibleTreasures(discardVisible);
        napakalakiModel.discardHiddenTreasures(discardHidden);
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jBdiscardTreasuresActionPerformed

    private void jBdAtreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdAtreasuresActionPerformed
        playerModel.discardAllTreasures();
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jBdAtreasuresActionPerformed

    private void jBstealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBstealActionPerformed
        playerModel.stealTreasure();
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jBstealActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdAtreasures;
    private javax.swing.JButton jBdiscardTreasures;
    private javax.swing.JButton jBmakeVisible;
    private javax.swing.JButton jBsteal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLenemy;
    private javax.swing.JLabel jLesSectario;
    private javax.swing.JLabel jLnCombate;
    private javax.swing.JLabel jLnSectarios;
    private javax.swing.JLabel jLnivel;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JPanel jPhiddenTreasures;
    private javax.swing.JPanel jPvisibleTreasures;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlavelg;
    private GUI.PendingBadConsequenceView pendingBadConsequenceView2;
    // End of variables declaration//GEN-END:variables
}
